_wandb:
    value:
        cli_version: 0.28.0
        e:
            qjoc4kefvfg8erzne57whht47kxkjn8i:
                args:
                    - --budget_frame_multiplier=5
                    - --eval_frame_stride=10
                    - --layer_budget_alpha=0
                    - --layer_budget_value_gamma=0
                    - --leverage_conf_gate_depth_alpha=0
                    - --leverage_conf_gate_floor=0
                    - --leverage_conf_gate_init=mean
                    - --leverage_conf_gate_k=1
                    - --leverage_conf_gate_point_beta=0
                    - --leverage_conf_gate_special_mode=mean
                    - --leverage_ridge_dim=96
                    - --max_frames=500
                    - --num_processes=3
                codePath: tools/wandb_mv_recon_sweep.py
                codePathLocal: tools/wandb_mv_recon_sweep.py
                email: vwjdehdwov@gmail.com
                executable: /opt/conda/envs/OVGGT/bin/python
                git:
                    commit: 8aed0af22526f876944dec25438c87fb6a92df7d
                    remote: https://github.com/D2-Bro/SStreamVGGT.git
                host: 40e28fcc17db
                os: Linux-5.15.0-126-generic-x86_64-with-glibc2.35
                program: /home/dongjae/SStreamVGGT/tools/wandb_mv_recon_sweep.py
                python: CPython 3.11.15
                root: /home/dongjae/SStreamVGGT
                startedAt: "2026-07-06T08:29:47.003320Z"
                writerId: qjoc4kefvfg8erzne57whht47kxkjn8i
        m: []
        python_version: 3.11.15
        t:
            "3":
                - 2
                - 14
            "4": 3.11.15
            "5": 0.28.0
            "12": 0.28.0
            "13": linux-x86_64
base_script:
    value: src/eval/mv_recon/launch.py
budget_frame_multiplier:
    value: "5"
eval_frame_stride:
    value: 10
layer_budget_alpha:
    value: 0
layer_budget_norm_source:
    value: key
layer_budget_value_gamma:
    value: 0
layer_budget_value_norm_type:
    value: mean
leverage_conf_gate_depth_alpha:
    value: 0
leverage_conf_gate_floor:
    value: 0
leverage_conf_gate_init:
    value: mean
leverage_conf_gate_k:
    value: 1
leverage_conf_gate_point_beta:
    value: 0
leverage_conf_gate_special_mode:
    value: mean
leverage_random_seed:
    value: 42
leverage_ridge_dim:
    value: 96
main_process_port:
    value: 29647
max_frames:
    value: 500
num_processes:
    value: 3
output_dir:
    value: /home/dongjae/SStreamVGGT/eval_results/mv_recon/wandb_wi93lhiu_headNorm_a0_g0_dim96_confGateFloor0_confGateDepthAlpha0_confGatePointBeta0_confGateK1_evalStride10_budgetFrameMult5
reference_script:
    value: src/eval/mv_recon/run_termProject_topK_conf_headNorm_evalStride_best.sh
total_budget:
    value: 200000
weights:
    value: ../ckpt/checkpoints.pth
